name: CI

on: [push, pull_request]

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Cache pnpm modules
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Log cache key
        run: echo "Cache key:${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}"

  lint:
    runs-on: ubuntu-latest
    needs: cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier check
        run: pnpm run format

      - name: Run Linter check
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm run test
